language: node_js
node_js:
  - "10"

install:
  - cd functions/app
  - npm install

script:
  - npm run test

cache:
  directories:
    - node_modules

notifications:
  email:
    - infojasyrc@gmail.com
